name: Run tests on pull requests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  OPENAI_API_KEY: dummy_key

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run test suite (Python ${{ matrix.python-version }})

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Pull Microsoft's Phi3 model
        run: ollama pull phi3

      - name: Setup Pixi Environment
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.25.0
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Run tests (pixi)
        run: |
            pixi run test

      # https://github.com/codecov/codecov-action
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          # fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

  smoke-tests:
    runs-on: ubuntu-latest
    name: Run smoke tests (Python ${{ matrix.python-version }})

    strategy:
      matrix:
        python-version: [3.11, 3.12]
        environment-type: ['pixi', 'bare']
    steps:
      - name: Test CLI (bare)
        if: matrix.environment-type == 'bare' && github.repository_owner == 'ericmjl'
        run: |
          pip install .
          llamabot --help

      - name: Test CLI (pixi)
        if: matrix.environment-type == 'pixi' && github.repository_owner == 'ericmjl'
        run: |
          pixi run llamabot-cli
