name: Run tests on pull requests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  OPENAI_API_KEY: dummy_key

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run test suite (Python ${{ matrix.python-version }}, ${{ matrix.environment-type }})

    strategy:
      matrix:
        python-version: [3.11]
        environment-type: ['bare', 'pixi']

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Pull Microsoft's Phi3 model
        run: ollama pull phi3

      - name: Setup Python environment
        if: matrix.environment-type == 'bare'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Pixi Environment
        if: matrix.environment-type == 'pixi' && github.repository_owner == 'ericmjl'
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.25.0
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}

      - name: Install dependencies
        if: matrix.environment-type == 'bare'
        # 17 June 2023: Figure out a way to move testing deps to the `pip install -e .` step below.
        run: |
          python -m pip install -e ".[all]"

      - name: Run tests (bare)
        if: matrix.environment-type == 'bare'
        run: |
          pip install -e ".[all]"
          pytest

      - name: Run tests (pixi)
        if: matrix.environment-type == 'pixi' && github.repository_owner == 'ericmjl'
        run: |
            pixi run test

      - name: Test CLI (bare)
        if: matrix.environment-type == 'bare'
        run: |
          pip install -e ".[all]"
          llamabot --help

      - name: Test CLI (pixi)
        if: matrix.environment-type == 'pixi' && github.repository_owner == 'ericmjl'
        run: |
          pixi run llamabot-cli

      # https://github.com/codecov/codecov-action
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          # fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
